### ISSUE TITLE
Training Complete

### ISSUE THREAD

**Issue by droter** [rafiuddinkhan/Yolo-Training-GoogleColab#1]
Hi,

Thanks for putting together this information.

I ran through the training with your data and it ran over 10 hours.  How do we know that the training is done or good enough?

Matt

**Comment by rafiuddinkhan** [comment]
Hello,
When training starts, the weights file are saved after every 1000 epoch to the backup folder of the darknet directory. And as far as how good the training did, you can keep track of the avg loss and see if less or near to 0.06 then it's the best and you can stop training. For crosscheck, you can stop the training at 1000 epoch and check the results and see if it's predicting the object suitable to you.
